# Railway project configuration

[project]
name = "DopeWalletBot"

description = "Solana wallet bot with onboarding, splash animation, and professional UI."

[services.frontend]
root = "frontend"
start = "npm run dev"

[services.backend]
root = "."
start = "npm start"

[env]
NEXT_PUBLIC_BACKEND_URL = "https://dopewalletbot-production.up.railway.app"
SUPABASE_URL = "your-supabase-url"
SUPABASE_KEY = "your-supabase-key"
RPC_URL = "your-solana-rpc-url"
